kind: pipeline
name: default
type: docker

steps:
  - name: lint
    image: golang
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1
      - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.41.1
      - go fmt ./...
      - golangci-lint run
      - go vet ./...

  - name: test
    image: golang
    commands:
      - go test -v ./...